name: "Rejseplanen Fetcher"
version: "1.0.1"
slug: "rejseplanen"
description: "Fetch Rejseplanen data and publish to MQTT"
url: "https://github.com/cajo-dk/hass-rejseplanen"
startup: services
boot: auto
host_network: true
arch:
  - amd64
  - aarch64
  - armv7
options:
  rejseplanen_access_id: ""
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_topic: ""
  mqtt_username: ""
  mqtt_password: ""
  mqtt_client_id: ""
  mqtt_qos: 0
  mqtt_tls: false
  rejseplanen_max_journeys: 80
  rejseplanen_duration: 60
schema:
  rejseplanen_access_id: str
  mqtt_host: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_username: str?
  mqtt_password: password?
  mqtt_client_id: str?
  mqtt_qos: int(0,2)
  mqtt_tls: bool
  rejseplanen_max_journeys: int(1,500)
  rejseplanen_duration: int(1,1440)
